/run/initialize
/tracking/verbose 0

/gun/particle gamma
/gun/pos 0 0 0 mm
/gun/dir 0 0 1


/gps/pos/type Plane
/gps/pos/shape Circle
/gps/pos/centre -17.5981 17.5981 -9.5322 cm 
/gps/pos/radius 1.5 mm
/gps/pos/rot1 1 1 0
/gps/pos/rot2 0 0 1

/gps/ang/type iso
/gps/ang/rot1 1 1 0
/gps/ang/rot2 0 0 1
/gps/ang/mintheta 1.57079633 rad
/gps/ang/maxtheta 3.14159265 rad

/run/printProgress 1000000
#/run/beamOn 3000000000
