/run/initialize
/tracking/verbose 0

# Particle generator
/generator/setMode neutrons
/generator/setAngle 45
/generator/setDistance 60.8

# Make sure you always have this line below with the same value as the one in '/generator/setAngle'
# This line rotates the far-side detectors an angle corresponding to the generator position
/placement/definePMTAngle 45

# Place the far-side detectors. The distances are in unit of cm
#/placement/addAngle1 6.738
#/placement/setDistance 151.65

/placement/addAngle2 9.941
/placement/setDistance 149.55

#/placement/addAngle3 15.855
#/placement/setDistance 149.25

/placement/addAngle4 20.66
/placement/setDistance 149.8

#/placement/addAngle5 26.26
#/placement/setDistance 148.4

/placement/addAngle6 31.93
/placement/setDistance 131.65

#/placement/addAngle7 38.63
#/placement/setDistance 117.75

/placement/addAngle8 55.79
/placement/setDistance 109.1

/placement/addAngle9 87.638
/placement/setDistance 82.4

#/placement/addAngle10 88.84
#/placement/setDistance 135.9

/run/printProgress 1000000
/run/beamOn 100000000
# with floor, slower
#/run/beamOn 400000000
